### ISSUE TITLE
Rewrite Networks List with FSD + Effector

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1455]
### Description
In order to increase maintainability and testability of Networks list, we must rewrite that part of code according to FSD with help of effector.

What needs to be done:
- [x] Networks list feature (or widget)
- [x] Support 2 lists: active / inactive networks
- [x] Persist existing filtration mechanism
- [x] Tests

**Comment by Tbaut** [comment]
I've had a look at the code in this part of the app and would appreciate some guidance
- Currently, network list are variables passed as props to `NetworkList`, derived from `$chains`, an effector store. Should I create 2 new stores [active/inactive]NetworkList and then use them in the `NetworkList` component instead of using props?
- is there anything else you mean by "Networks list feature (or widget)" and "Support 2 lists: active / inactive networks" that I didn't describe in the above point?
- query is a common react state (using `useState`) right now, we should create a store for it instead and use effector events to mutate it etc. Anything else I'm missing?

I'll concentrate on the feature in a first place, and ask further/later regarding tests.

**Comment by tuul-wq** [comment]
> query is a common react state (using useState) right now, we should create a store for it instead and use effector events to mutate it etc. Anything else I'm missing?
You're right. We should use $query store to work with filtering mechanism
Search for `$query` in project, there are a bunch of similar filters

> Support 2 lists: active / inactive networks
Just meant that these features should not be lost during refactoring 😉

> Networks list feature (or widget)
We should decide `<NetworksList>` is a feature or a widget in terms of FSD. Widget consists of features, and one of them would be NetworkSelector. 

> Should I create 2 new stores [active/inactive]NetworkList and then use them in the NetworkList
Yes, these 2 stores should be derived via `combine` from networkModel.$chains depending on `connectionStatus`
