### ISSUE TITLE
Add delegated authority for single chain multisig - lead to error

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1727]
## Description
When user try to create delegated authority for single chain multisig, which was created in not supported network (e.g. Acala) the app will crash.

## Steps to Reproduce

1. Create Single Chain multisig in Acala
2. Go to Multisig details
3. Try to create delegated authority

## Expected Behavior
Can't create delegated authority in network, where it does not support

## Actual Behavior
The app fall down

## Environment
https://github.com/novasamatech/nova-spektr/commit/670671401c8f4e08907515f4a1ba061d895fe45a

log:
[nova-spektr.log](https://github.com/novasamatech/nova-spektr/files/15091557/nova-spektr.log)

<img width="300" alt="Screenshot 2024-04-24 at 12 03 05" src="https://github.com/novasamatech/nova-spektr/assets/40560660/09d8ee48-bb4b-4f0a-9273-b1e470cf9fe0">

**Comment by pgolovkin** [comment]
Reproduced for `Add pure proxy`.

**Comment by pgolovkin** [comment]
**The solution:**
Hide `Add pure proxy`, `Add delegated authority` buttons  for wallets where networks with proxy are not supported.

**Comment by Tbaut** [comment]
Is this "single chain" or "multi chain" multisig something we specify in Nova, and that is only known to the app?

I find this concept a little hard to grasp, that's something we set in the DB right? what if you've created a multisig outside of Nova, this "multi" or "single" will not be known right?

pinging @pgolovkin if you can give additional context. To me, if this is something that is on-chain, or can be derived from it, then it makes sense, if it's not, I believe we should forget about it, because this will only create confusion.

**Comment by stepanLav** [comment]
Status verification: ✅

**Comment by pgolovkin** [comment]
> Is this "single chain" or "multi chain" multisig something we specify in Nova, and that is only known to the app?
> 
> I find this concept a little hard to grasp, that's something we set in the DB right? what if you've created a multisig outside of Nova, this "multi" or "single" will not be known right?
> 
> pinging @pgolovkin if you can give additional context. To me, if this is something that is on-chain, or can be derived from it, then it makes sense, if it's not, I believe we should forget about it, because this will only create confusion.

Let me share historical context.
1. In terms of the Milestone 2 the multisig feature was developed. It was a `multichain multisig`. Multichain multisig means that the same AccountId of the multisig is being used for all networks that has a `multisig` pallet and integrated into the Nova Spektr. Multichain mutlisig assumes that signatories are using same accounts (public keys) and same threshold on different chains (as a result multisig address (accountId) is the same for all networks). This type of multisig 
2. In terms of the Milestone 3 a single chain multisig was introduced. It works only on the chain that was selected by the user when creating a multisig wallet. So it's more closely to what Multix does.

I think that in the Milestone 4 only single chain multisigs will be supported because:
1. The user has to create `system_remark` or `proxy_createPure` transaction when creates a multisig. Transaction has to be made on chain that the user selects when creates a multisig wallet - so it's a single chain multisig
2. The indexer for multisigs works on a specific chain and it's really hard to merge a set of single chain accounts to a multichain account.
3. Single chain multisigs are much easier to support

**Comment by Tbaut** [comment]
Thanks, I now understand that this distinction is indeed a Spektr thing and comes from previous milestones, and this is why I didn't really understand. I think we should remove this step of selecting between the 2, and talk about multisig overall because indeed, with on-chain discovery, there's no way to know whether it's a single chain or multi chain. What we can do is treat a simple multisig (without pure) as a multichain (Spektr has no chain selection after all) and any flexible multisig as a single chain (that's where a pure proxy was created). What do you think?

**Comment by pgolovkin** [comment]
> Thanks, I now understand that this distinction is indeed a Spektr thing and comes from previous milestones, and this is why I didn't really understand. I think we should remove this step of selecting between the 2, and talk about multisig overall because indeed, with on-chain discovery, there's no way to know whether it's a single chain or multi chain. What we can do is treat a simple multisig (without pure) as a multichain (Spektr has no chain selection after all) and any flexible multisig as a single chain (that's where a pure proxy was created). What do you think?

Glad to hear!
I agree that selecting between multichain and singlechain multisig should be removed and all multisigs should be single chain.
Instead of this the user should be able to select if he'd like to create a `simple multisig` (naming should be clarified) - without pure proxy or `flexible multisig` - with pure proxy.

So my summary is:
1. Remove multichain multisig support
2. Instead of selection between single chain and multichain multisig the user should select between `simple multisig` and `flexible multisig`
