### ISSUE TITLE
Redo the multisig creation to create a system.remark call

### ISSUE THREAD

**Issue by Tbaut** [novasamatech/nova-spektr#1756]
With the removal of matrix, and the new way of discovering multisigs, the multisig creation now consists in:
- making a multisig tx, any really, a system.remark is a simple one. It serves as a nice firt tx for users, but it's not necessary to be signed by everyone.
- the indexer picks it up
- the UI shows it

Any chance we can have mockups and a brainstorming sessions @pgolovkin 
Some questions:
- what happens when the Tx is sent, but the indexer still didn't pick it up (I need to check how long it takes exactly)?
- should we 
  - make polling every 5s then instead of 30 for this time
  - or do we actually create the multisig in the DB, show it, and the pending multisig tx will eventually appear? (I prefer this way)

**Comment by pgolovkin** [comment]
@Tbaut 
For sure let's have brainstorm and mockups review session (will DM you).
I'm going to answer here to be transparent as well.
The flow that you've described is correct: Nova Spektr creates a multisig tx (`system_remark` or `proxy_createPure`), indexer picks it up, the UI on other signatory's Nova Spektr instance creates a multisig wallet and adds a notification.

Thanks for pointing to corner cases! I'm going to share my vision, however keep in mind that it's not a final decision and it will be good to discuss it. I'm going to split my answer it 2 parts: multisig discovery (getting multisig account form indexer) and getting multisig Tx.

# Getting multisig Tx
If the TX is sent but the indexer still didn't pick it up then the multisig signatory with Nova Spektr won't get the multisig account in his (her) Nova Spektr app. 
So the signatory's Nova Spektr instance doesn't know anything about other signatory's action (actions), as a result how the Nova Spektr can make a decision to start polling more often (5s instead of 30s)?
I think that depending on the result of checking how long Tx indexing takes the decision about polling interval should be made.

# Creating multisig account
When the multisig Tx is received from the indexer the Nova Spektr has to make the following steps of actions:
1. Check if the multisig wallet with the multisig account from the Tx is already stored in the Nova Spektr database.
1.1. If multisig wallet with the multisig account exists then save the Tx in the Nova Spektr database
1.2. Else create the multisig wallet with the multisig account in the Nova Spektr database. Save the Notification in the Nova Spektr database. Create the multisig Tx in the Nova Spektr database

Saving Notifications, Multisig wallet with multisig account, multisig Tx is already implemented in Nova Spektr. There are 2 things that should be changed:
1. The event that results to entity creation: for Multisig wallet it was Matrix now it will be Tx (the same for the Notification) from the indexer, for the multisig Tx it was multisig pallet storage or Matrix now it will be indexer and multisig pallet storage.
2. The data source for data in Nova Spektr database: for Multisig wallet it was Matrix now it will be Tx (the same for the Notification) from the indexer, for the multisig Tx it was multisig pallet storage or Matrix now it will be indexer and multisig pallet storage

**Comment by pgolovkin** [comment]
Mockups [link](https://www.figma.com/file/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?type=design&node-id=0%3A1&mode=design&t=YC2w5PSVSXm5DDdG-1)

**Comment by pgolovkin** [comment]
@Tbaut please check the doc with [requirements that i've prepared for designer](https://docs.google.com/document/d/1R1G5HoabNoUBweE0UhfRETIF9LdRcUQqGDRf28I_Umk/edit#heading=h.jnqjv4tjlt1m). It may be useful.

In terms of this task let's focus on **non-flexible** multisig only.

**Comment by pgolovkin** [comment]
@Tbaut please check mockups for creating multisig without Matrix:

1. Multisig creation [prototype](https://www.figma.com/proto/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?page-id=0:1&node-id=518-88080&viewport=73,491,0.03&t=pRppgwa1U82gQVms-1&scaling=min-zoom&starting-point-node-id=518:88080&show-proto-sidebar=1) (Flow 2)
2. Remark for the 1st point. There shouldn't be multisig type selection because we're not working on Flexible multsigs right now 
3. Flows 6, 7 are out of scope of the Milestone 4
4. Getting Notifcation about [getting multisig from blockhain](https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=445-30217&t=SFYzfrFNuqK5AMJ8-4)

**Comment by Tbaut** [comment]
this is closed with #1800

**Comment by leohar** [comment]
Status verification: ✅ 

What has been verified:
* https://westend.subscan.io/account/5EFfJ65cVk9V2FRvmzc6CBASLs9Gf5LFjGMoXa1QxGcMXkyL?tab=multisig_extrinsic
