### ISSUE TITLE
Can't sign operations from time to time

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1941]
## Description
When user try to sign regular transfer - got an `ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature`, but if add it to the basket and sigh there - that will work properly.

<img width="500" alt="Screenshot 2024-07-10 at 17 51 46" src="https://github.com/novasamatech/nova-spektr/assets/40560660/358c6138-1187-468e-95f8-e30cfae0da64">

## Steps to Reproduce

1. Go to Portfolio page
2. Create Westend transfer
3. Try to sign it

## Expected Behavior
Successfully signed the operation

## Actual Behavior
ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature

## Environment
https://github.com/novasamatech/nova-spektr/commit/f3287cf5439fb28de44822ff6fb2a64a18f87b22

**Comment by pgolovkin** [comment]
Add logging for diagnostic for each transaction. Logging should be made after signing and log:
1. Chain
2. Operation name
3. nonce
2. encoded operation
3. unsigned transaction
4. signed transaction

Using this logging developers will be able to track signed transactions from log and figure out the root cause of the problem.
