### ISSUE TITLE
Flexible multisig. Delete wallet procedur update

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2439]
The problem:
1. The user removes the multisig wallet
2. The multisig worker adds the multisig wallet back into the Spektr

**Comment by sokolova-an** [comment]
As discussed, we won’t delete the wallet from the database but rather hide it from the user so it won’t appear in their list of wallets. A few design-related questions:

1.	Will we display a message to the user when they delete their multisig wallet, explaining that it’s not actually deleted, and if they want access again, they will need to restore it manually by adding the same signatories in the multisig creation flow?
2.	Since we’re keeping the wallet in the database, if the user creates a new multisig with the same signatories as the hidden wallet, should we show them a suggestion to restore the hidden multisig instead of creating a new one?

**Comment by leohar** [comment]
Status verification: ✅ 

What has been verified:
* remove ms account and restore
* repeat 1st step once again
* remove ms as last wallet
* regression on wallet removal on all wallet types

issues:
* can continue  with the same params on restore with ms creation flow 
* ms wallet name on restore is not applied @sokolova-an should we do smth with this?
