### ISSUE TITLE
Multisig. Create multisig. Account selection should show possible value when in focus

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2490]
## Description

Example:

https://github.com/user-attachments/assets/ffc7319a-e5b6-4614-af60-30f050bd5cd1

**Expected result:**

Show possible values when field in focus

## Environment
https://github.com/novasamatech/nova-spektr/commit/6ca515af94bd4d44ea25ada390bcc01455cd4bc4

**Comment by Tbaut** [comment]
This is an issue I had identified in the past, and the clean way to fix this is to use a new property in the headlessUI component. See https://github.com/novasamatech/nova-spektr/pull/1931
Now since this is a much larger refactoring we agree not to deal with it now.
This behavior would be much much better in many other places of Spektr, such as the transfer component, where you could see and select the addresses from your address book for the recipient.

My message a while ago:
![image](https://github.com/user-attachments/assets/7a3886f2-bafc-47cc-a055-90679806c94c)

**Comment by stepanLav** [comment]
Status verification: ✅
