### ISSUE TITLE
Multisig. Create multisig flow. Wrong name assign for signatory.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2492]
## Description
When user has wallet with name and contact with another name, assign signatory from contacts will assign name from wallets

Example:

https://github.com/user-attachments/assets/d90b4a03-1453-47f7-829a-5b526eb86ec3

## Environment
https://github.com/novasamatech/nova-spektr/commit/6ca515af94bd4d44ea25ada390bcc01455cd4bc4

**Comment by Tbaut** [comment]
This should only be possible if you have 2 contacts with the same address in the contact address book, which is a state we should never be in. Is that possible?
I know this was a bug (in the address book) that seems to have been solved by now, by modifying the address book code I could reproduce. Now this should never happen.

The way it is implemented, is that we take the address as the source of truth (so that you can copy/paste an address) and then I look in the contact list whether this address is known, in case the user didn't go from the list. This way, and since we should only have 1 name per address, the user can paste or select, and still get the name.

https://github.com/user-attachments/assets/c4ef952a-78e2-494d-970a-422276a3b789

**Comment by pgolovkin** [comment]
@Tbaut it's a problem when the contact and wallet have same address.

**Comment by Tbaut** [comment]
@pgolovkin , should this be prevented then? There shouldn't be any instance of a same address having 2 names in the interface in my opinion. doing anything at this level will simply hide the real problem: there shouldn't be duplicated name/addresses.

**Comment by pgolovkin** [comment]
@Tbaut I think that component should work as expected and show what was selected `aaa -> aaa`, `zzz -> zzz`.

**Comment by Tbaut** [comment]
Did you read my comment? Are you implying that it's fine that the same address has 2 different names in Spektr?

**Comment by Tbaut** [comment]
I added a workaround.. although I don't think it's the right approach. https://github.com/novasamatech/nova-spektr/pull/2521
