### ISSUE TITLE
Multisig. Constant fee loading state

### ISSUE THREAD

**Issue by leohar** [novasamatech/nova-spektr#2533]
## Description

After some time in background or alive fee is not loaded, also wallet indicator is grey

Example:

![Image](https://github.com/user-attachments/assets/855ec8b5-a3c0-41ea-8af8-a7628f86d4e5)

https://github.com/user-attachments/assets/45fd8387-10fd-43fe-a659-2764ea56a882

**Expected result:**

fee is loaded

## Environment
https://github.com/novasamatech/nova-spektr/pull/2520

**Comment by Tbaut** [comment]
This is happening most probably on any interface with such fee display since this is the same component that I use here. So if anything, then it's not a bug that is specifically linked to this modal. From your screenshot, there seem to have been an "Abnormal closure" of the RPC connection is that right? In any case I agree there should be a better handling of such cases.

**Comment by pgolovkin** [comment]
@Tbaut yes, right. I've checked it with connected Westend and fee is shown on the 1st screen.
