### ISSUE TITLE
Icons. Make colored icons in Spektr

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2546]
Allow the user to use color icon for tokens.

1. Update portfolio page
2. Update create operation flow
3. Update operation page

By default the colored icons has to be used.
For current users Spektr has to be switched to colored icons.

Colored icons repo link https://github.com/novasamatech/nova-utils/pull/3117

**Comment by johnthecat** [comment]
My proposal:
* Introduce `iconStyle` flag in `<ThemeProvider/>` from `ui-kit`
* Move `<AssetIcon/>` to `ui-entities`
* Change API of `<AssetIcon/>` component, it should get whole Asset type and decide which icon should be rendered inside itself. Black backdrop should be moved inside component as well because it's part of the logic around monochrome icon style.

**Comment by stepanLav** [comment]
Status verification: ✅
